// Generate src/tables.ts from DOOM/linuxdoom-1.10/tables.{h,c}.
//
// finesine/finetangent/tantoangle are baked lookup tables, not conveniences.
// Recomputing them from Math.sin would give ALMOST the same numbers, which is
// the worst outcome available: right enough to look fine, wrong enough to
// desync a demo. The physics was tuned against these exact values with their
// exact rounding, so extract them verbatim.
//
//   node tools/gen-tables.js
//
// Writes src/tables.ts directly rather than to stdout — a redirect makes the
// invocation a shell construct, and errors would clobber the output file.

import { readFileSync, writeFileSync } from 'node:fs';

const OUT = 'src/tables.ts';

const SRC = 'DOOM/linuxdoom-1.10';
const c = readFileSync(`${SRC}/tables.c`, 'utf8');

const decomment = (s) => s.replace(/\/\*[\s\S]*?\*\//g, '').replace(/\/\/[^\n]*/g, '');

/** Pull `type name[N] = { ... };` and parse its integer literals. */
function parseTable(src, name) {
  const decl = new RegExp(`\\b${name}\\s*\\[\\s*(\\d+)\\s*\\]\\s*=`);
  const m = decl.exec(src);
  if (!m) throw new Error(`table ${name} not found`);
  const declared = parseInt(m[1], 10);

  const open = src.indexOf('{', m.index);
  const close = src.indexOf('};', open);
  if (open < 0 || close < 0) throw new Error(`table ${name}: no body`);

  const body = decomment(src.slice(open + 1, close));
  const vals = [];
  for (const tok of body.split(',')) {
    const t = tok.trim();
    if (!t) continue;
    // Values are plain decimal ints, some negative, occasionally 0x hex.
    const n = /^-?0x[0-9a-fA-F]+$/.test(t) ? parseInt(t, 16) : parseInt(t, 10);
    if (Number.isNaN(n)) throw new Error(`table ${name}: bad literal ${JSON.stringify(t)}`);
    vals.push(n);
  }
  if (vals.length !== declared) {
    throw new Error(`table ${name}: parsed ${vals.length}, declared ${declared}`);
  }
  return vals;
}

const finetangent = parseTable(c, 'finetangent');
const finesine = parseTable(c, 'finesine');
const tantoangle = parseTable(c, 'tantoangle');

// ---- sanity: these must agree with trig to within the tables' own rounding --
const errs = [];
if (finetangent.length !== 4096) errs.push(`finetangent ${finetangent.length} != 4096`);
if (finesine.length !== 10240) errs.push(`finesine ${finesine.length} != 10240`);
if (tantoangle.length !== 2049) errs.push(`tantoangle ${tantoangle.length} != 2049`);

// finesine[i] should be sin(i * 2pi/8192) * 65536. Check the well-conditioned
// part (near the peak, away from where rounding dominates).
let worst = 0;
for (let i = 0; i < 8192; i++) {
  const want = Math.sin(((i + 0.5) * 2 * Math.PI) / 8192) * 65536;
  worst = Math.max(worst, Math.abs(finesine[i] - want));
}
if (worst > 2) errs.push(`finesine deviates from sin() by ${worst} — parsed wrong?`);

// finecosine is finesine offset by a quarter turn; verify the aliasing holds.
for (let i = 0; i < 100; i++) {
  if (finesine[i + 2048] !== finesine[(i + 2048) % 8192]) {
    errs.push('finesine quarter-turn aliasing broken');
    break;
  }
}

if (errs.length) {
  console.error('gen-tables: ' + errs.join('\n            '));
  process.exit(1);
}

const j = (v) => JSON.stringify(v);
writeFileSync(OUT, `// GENERATED by tools/gen-tables.js from ${SRC}/tables.c — do not edit.
//
// Baked LUTs, extracted verbatim rather than recomputed: the physics was tuned
// against these exact values and their exact rounding. Max deviation from
// Math.sin over the full circle: ${worst.toFixed(3)} (in 16.16 fixed).

export const FINEANGLES = 8192;
export const FINEMASK = FINEANGLES - 1;
export const ANGLETOFINESHIFT = 19;

export const SLOPERANGE = 2048;
export const SLOPEBITS = 11;
export const DBITS = 16 - SLOPEBITS;

/** 5*FINEANGLES/4 entries: a full circle plus a quarter, so finecosine can alias in. */
export const finesine: Int32Array = new Int32Array(${j(finesine)});

/** finecosine is finesine shifted a quarter turn — the same storage, no second table. */
export const finecosine: Int32Array = finesine.subarray(FINEANGLES / 4);

export const finetangent: Int32Array = new Int32Array(${j(finetangent)});

export const tantoangle: Uint32Array = new Uint32Array(${j(tantoangle)});
`);

console.error(`gen-tables: wrote ${OUT} — finesine ${finesine.length}, ` +
              `finetangent ${finetangent.length}, tantoangle ${tantoangle.length}, ` +
              `max trig deviation ${worst.toFixed(3)}`);
