import type { PostEffect } from './effect.js';

// Pen-and-ink cross-hatching via a Tonal Art Map (Praun/Hoppe, "Real-Time
// Hatching"), and a demo of the iChannel URL loader. The TAM is six nested
// hatch levels (texture/TAMStack, generated by scripts/gen-tam.mjs), loaded as
// an array channel. Two ideas from the paper:
//  1. Hatching lives in SURFACE space, so (like the matrix effect) we reconstruct
//     iWorldPos and project the TAM triplanar-ally onto the surface.
//  2. Tone picks the level. DOOM's shading is near-flat, so we FAKE the light off
//     the G-buffer normals (key + fill, N.L), flipping the geometric normal to
//     face the camera. Darker tone -> a denser level; the two levels bracketing
//     the tone are blended (the TAM's nesting keeps that from popping), and the
//     level is thinned with distance so far surfaces don't turn to mud.
export const crosshatch: PostEffect = {
  name: 'crosshatch',
  author: 'Claude',
  hidden: true,
  wgsl: `
// iChannel1:
//   layers:
//     - texture/TAMStack/tam0.png
//     - texture/TAMStack/tam1.png
//     - texture/TAMStack/tam2.png
//     - texture/TAMStack/tam3.png
//     - texture/TAMStack/tam4.png
//     - texture/TAMStack/tam5.png
fn mainImage(fragCoord: vec2f) -> vec4f {
  let uv = fragCoord / U.iResolution.xy;
  let grain = iChan(iNoiseValue, fragCoord / 512.0).r;
  let paper = vec3f(0.94, 0.92, 0.86) * (0.93 + 0.07 * grain);

  // Reconstruct the surface, flip its normal to face the camera, fake-light it.
  let P = iWorldPos(uv);
  var N = normalize(iNormal0(uv));
  N = N * select(1.0, -1.0, dot(N, normalize(U.iCamPos - P)) < 0.0);
  let key = normalize(vec3f(0.5, 0.8, 0.35));
  let fill = normalize(vec3f(-0.6, 0.25, -0.4));
  let tone = clamp(0.16 + 0.74 * max(dot(N, key), 0.0) + 0.22 * max(dot(N, fill), 0.0), 0.0, 1.0);

  // Triplanar surface coordinate so strokes lie ON the surface.
  let aN = abs(N);
  var suv = P.xy;
  if (aN.y >= aN.x && aN.y >= aN.z) { suv = P.xz; }
  else if (aN.x >= aN.z) { suv = P.zy; }
  let huv = suv / 224.0;                                          // world units per TAM tile

  // Tone -> TAM level (dark = denser), thinned with distance; blend the two
  // levels bracketing it. Samples are unconditional (keeps them in uniform flow).
  let d = iDepth0(uv);
  let lvl = clamp((1.0 - tone) * 5.0 - clamp((d - 300.0) / 3000.0, 0.0, 2.5), 0.0, 5.0);
  let l0 = floor(lvl);
  let a = textureSample(iChannel1, iChannelSampler, huv, i32(l0)).r;
  let b = textureSample(iChannel1, iChannelSampler, huv, i32(min(l0 + 1.0, 5.0))).r;
  let cover = mix(a, b, lvl - l0);                                // 1 = paper, 0 = ink
  let hatched = mix(vec3f(0.10, 0.09, 0.12), paper, cover);

  if (d < 1.0) { return iColor0(uv); }                            // UI / weapon
  if (iDepth01(uv) >= 0.999) { return vec4f(paper, 1.0); }        // sky / far
  return vec4f(hatched, 1.0);
}`,
  glsl: `
// iChannel1:
//   layers:
//     - texture/TAMStack/tam0.png
//     - texture/TAMStack/tam1.png
//     - texture/TAMStack/tam2.png
//     - texture/TAMStack/tam3.png
//     - texture/TAMStack/tam4.png
//     - texture/TAMStack/tam5.png
void mainImage(out vec4 fragColor, in vec2 fc) {
  vec2 uv = fc / iResolution.xy;
  float grain = iChan(iNoiseValue, fc / 512.0).r;
  vec3 paper = vec3(0.94, 0.92, 0.86) * (0.93 + 0.07 * grain);

  vec3 P = iWorldPos(uv);
  vec3 N = normalize(iNormal0(uv));
  if (dot(N, normalize(iCamPos - P)) < 0.0) N = -N;
  vec3 key = normalize(vec3(0.5, 0.8, 0.35));
  vec3 fill = normalize(vec3(-0.6, 0.25, -0.4));
  float tone = clamp(0.16 + 0.74 * max(dot(N, key), 0.0) + 0.22 * max(dot(N, fill), 0.0), 0.0, 1.0);

  vec3 aN = abs(N);
  vec2 suv = P.xy;
  if (aN.y >= aN.x && aN.y >= aN.z) suv = P.xz;
  else if (aN.x >= aN.z) suv = P.zy;
  vec2 huv = suv / 224.0;

  float d = iDepth0(uv);
  float lvl = clamp((1.0 - tone) * 5.0 - clamp((d - 300.0) / 3000.0, 0.0, 2.5), 0.0, 5.0);
  float l0 = floor(lvl);
  float a = texture(iChannel1, vec3(huv, l0)).r;
  float b = texture(iChannel1, vec3(huv, min(l0 + 1.0, 5.0))).r;
  float cover = mix(a, b, lvl - l0);
  vec3 hatched = mix(vec3(0.10, 0.09, 0.12), paper, cover);

  if (d < 1.0) { fragColor = iColor0(uv); return; }
  if (iDepth01(uv) >= 0.999) { fragColor = vec4(paper, 1.0); return; }
  fragColor = vec4(hatched, 1.0);
}`,
};
